/* AUTO-GENERATED by paper-crops/crop.py — verbatim paragraph image crops */
window.MLOPS_CROPS = {
"fp-0": [
"paper-crops/fp-0-0.png"
],
"fp-1": [
"paper-crops/fp-1-0.png"
],
"fp-2": [
"paper-crops/fp-2-0.png",
"paper-crops/fp-2-1.png"
],
"fp-3": [
"paper-crops/fp-3-0.png"
],
"fp-4": [
"paper-crops/fp-4-0.png"
],
"fp-5": [
"paper-crops/fp-5-0.png"
],
"fp-6": [
"paper-crops/fp-6-0.png"
],
"fp-7": [
"paper-crops/fp-7-0.png"
],
"fp-8": [
"paper-crops/fp-8-0.png"
],
"fp-9": [
"paper-crops/fp-9-0.png",
"paper-crops/fp-9-1.png"
],
"fp-10": [
"paper-crops/fp-10-0.png"
],
"fp-11": [
"paper-crops/fp-11-0.png",
"paper-crops/fp-11-1.png",
"paper-crops/fp-11-2.png"
],
"fp-12": [
"paper-crops/fp-12-0.png"
],
"fp-13": [
"paper-crops/fp-13-0.png"
],
"fp-14": [
"paper-crops/fp-14-0.png"
],
"fp-15": [
"paper-crops/fp-15-0.png"
],
"fp-16": [
"paper-crops/fp-16-0.png"
],
"fp-17": [
"paper-crops/fp-17-0.png"
],
"fp-18": [
"paper-crops/fp-18-0.png"
],
"fp-19": [
"paper-crops/fp-19-0.png"
],
"fp-20": [
"paper-crops/fp-20-0.png"
],
"fp-21": [
"paper-crops/fp-21-0.png"
],
"fp-22": [
"paper-crops/fp-22-0.png"
],
"fp-23": [
"paper-crops/fp-23-0.png"
],
"fp-24": [
"paper-crops/fp-24-0.png"
],
"fp-25": [
"paper-crops/fp-25-0.png"
],
"fp-26": [
"paper-crops/fp-26-0.png"
],
"fp-27": [
"paper-crops/fp-27-0.png"
],
"fp-28": [
"paper-crops/fp-28-0.png"
],
"fp-29": [
"paper-crops/fp-29-0.png"
],
"fp-30": [
"paper-crops/fp-30-0.png"
],
"fp-31": [
"paper-crops/fp-31-0.png"
],
"fp-32": [
"paper-crops/fp-32-0.png"
],
"fp-33": [
"paper-crops/fp-33-0.png"
],
"fp-34": [
"paper-crops/fp-34-0.png"
],
"fp-35": [
"paper-crops/fp-35-0.png"
],
"fp-36": [
"paper-crops/fp-36-0.png"
],
"fp-37": [
"paper-crops/fp-37-0.png"
],
"fp-38": [
"paper-crops/fp-38-0.png"
],
"fp-39": [
"paper-crops/fp-39-0.png"
],
"fp-40": [
"paper-crops/fp-40-0.png"
],
"fp-41": [
"paper-crops/fp-41-0.png"
],
"fp-42": [
"paper-crops/fp-42-0.png"
],
"fp-43": [
"paper-crops/fp-43-0.png"
],
"fp-44": [
"paper-crops/fp-44-0.png"
],
"fp-45": [
"paper-crops/fp-45-0.png"
],
"fp-46": [
"paper-crops/fp-46-0.png"
],
"fp-47": [
"paper-crops/fp-47-0.png"
],
"fp-48": [
"paper-crops/fp-48-0.png",
"paper-crops/fp-48-1.png"
],
"fp-49": [
"paper-crops/fp-49-0.png"
],
"fp-50": [
"paper-crops/fp-50-0.png"
],
"fp-51": [
"paper-crops/fp-51-0.png",
"paper-crops/fp-51-1.png"
],
"fp-52": [
"paper-crops/fp-52-0.png"
],
"fp-53": [
"paper-crops/fp-53-0.png"
],
"fp-54": [
"paper-crops/fp-54-0.png",
"paper-crops/fp-54-1.png"
],
"fp-55": [
"paper-crops/fp-55-0.png"
],
"fp-56": [
"paper-crops/fp-56-0.png"
],
"fp-57": [
"paper-crops/fp-57-0.png"
],
"fp-58": [
"paper-crops/fp-58-0.png",
"paper-crops/fp-58-1.png"
],
"fp-59": [
"paper-crops/fp-59-0.png"
],
"fp-60": [
"paper-crops/fp-60-0.png"
],
"fp-61": [
"paper-crops/fp-61-0.png"
]
};
